const assert=require('node:assert/strict');const m=require('../dist/model.js');
let passed=0;function test(name,f){f();passed++;console.log('PASS '+name);}
test('RGB–Lab round trip within one channel level',()=>{for(const rgb of [[0,0,0],[255,255,255],[40,90,130],[210,150,12],[255,0,0]])assert(m.labToRgb(m.rgbToLab(rgb)).every((v,i)=>Math.abs(v-rgb[i])<=1));});
test('exact two-color image learns both without invented third color',()=>{const r=m.analyze(Array.from({length:200},(_,i)=>i<150?[30,90,40]:[220,170,60]));assert.equal(r.clusters,2);assert(r.holdoutError<1e-6);assert.equal(r.colors[0].share,.75);});
test('constant image marked low variation and finite',()=>{const r=m.analyze(Array.from({length:100},()=>[70,70,70]));assert.equal(r.clusters,1);assert(r.lowVariation);assert(Number.isFinite(r.holdoutError));});
test('invalid pixels and cluster arguments rejected',()=>{for(const x of [[],[[NaN,0,0]],Array.from({length:20},()=>[256,0,0])])assert.throws(()=>m.analyze(x));assert.throws(()=>m.kmeans([[1,2,3]],0));});
test('deterministic fit and nonincreasing Lloyd objective',()=>{const p=Array.from({length:100},(_,i)=>[i%13,i%7,i%19]);const a=m.kmeans(p,5);assert.deepEqual(a,m.kmeans(p,5));a.history.forEach((x,i)=>{if(i)assert(x<=a.history[i-1]+1e-8);});});
test('shares normalized and heldout split exact',()=>{const r=m.analyze(Array.from({length:101},(_,i)=>[i*2,i,255-i]));assert(Math.abs(r.colors.reduce((s,c)=>s+c.share,0)-1)<1e-12);assert.equal(r.heldoutPixels,21);assert.equal(r.trainPixels,80);});
let seed=9;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const cases=[];
for(let n=0;n<30;n++){const centers=Array.from({length:3+n%3},()=>Array.from({length:3},()=>30+rand()*195));const pixels=Array.from({length:1000},()=>{const c=centers[Math.floor(rand()*centers.length)];return c.map(x=>Math.max(0,Math.min(255,Math.round(x+(rand()-.5)*18))));});const before=performance.now(),r=m.analyze(pixels);cases.push({case:n,pixels:1000,heldout_error:r.holdoutError,baseline_error:r.baselineError,ms:performance.now()-before});}
test('30 synthetic mixtures improve on one-mean baseline',()=>{assert(cases.every(c=>c.heldout_error<c.baseline_error));});
const report={created:new Date().toISOString(),environment:process.version,tests_passed:passed,synthetic_cases:cases.length,mean_heldout_deltaE76:cases.reduce((s,c)=>s+c.heldout_error,0)/cases.length,mean_baseline_deltaE76:cases.reduce((s,c)=>s+c.baseline_error,0)/cases.length,median_ms:cases.map(c=>c.ms).sort((a,b)=>a-b)[15],limits:'Synthetic numerical tests, not field observations, human study, species accuracy or browser QA.',cases};require('node:fs').writeFileSync('tests/results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,cases:undefined}));
